import Dashboard from "./Dashboard.jsx";
import Login from "./Login.jsx";
import Signup from "./Signup.jsx";
import Products from "./Products.jsx";
import Categories from "./Categories.jsx";
import Salesman from "./Salesman.jsx";
import Analytics from "./Analytics.jsx";
import Reports from "./Reports.jsx";
import Profile from "./Profile.jsx";
import Invoice from "./Invoice.jsx";
import AddProduct from "./AddProduct.jsx";
export { Dashboard, Login, Signup, Products, Categories, Salesman, Analytics, Reports, Profile, Invoice, AddProduct };